# Class 3 HW Part 1: numpy and scipy
Begin by importing the libraries that you'll need for today: numpy, matplotlib, pandas, and seaborn.

In [1]:
# import libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

## <font color = blue>Problem 1: a few basic problems on creating numpy arrays </font>
#### 1a.) Create a 10x5 numpy array "x" filled with ones, and print the data type of the first value of the first element.

In [9]:
#hint: is there a numpy function that makes this easier?
x = np.ones([10,5])
print('x[1,1] data type: ', x[1,1].dtype)
print('x: ',x)

x[1,1] data type:  float64
x:  [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


#### 1b.) Find two separate ways to create the same matrix "x", containing ints instead of floats

In [26]:
#hint: there are more than two ways! Just pick the two that are easiest for you.
x = np.ones([10,5],dtype=int)
print('x: ',x)
print('x[1,1] data type: ',x[1,1].dtype)
# x = 10x5 array of ones with datatype = int


x:  [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
x[1,1] data type:  int32


#### 1c.) Reassign x to a 1D array of 50 evenly spaced elements between 2 and 20, inclusive.

In [27]:
x = np.linspace(2,20,50,endpoint=True)
print('x linspace: ',x)

x linspace:  [ 2.          2.36734694  2.73469388  3.10204082  3.46938776  3.83673469
  4.20408163  4.57142857  4.93877551  5.30612245  5.67346939  6.04081633
  6.40816327  6.7755102   7.14285714  7.51020408  7.87755102  8.24489796
  8.6122449   8.97959184  9.34693878  9.71428571 10.08163265 10.44897959
 10.81632653 11.18367347 11.55102041 11.91836735 12.28571429 12.65306122
 13.02040816 13.3877551  13.75510204 14.12244898 14.48979592 14.85714286
 15.2244898  15.59183673 15.95918367 16.32653061 16.69387755 17.06122449
 17.42857143 17.79591837 18.16326531 18.53061224 18.89795918 19.26530612
 19.63265306 20.        ]


#### 1d.) Reassign x to a 1D array of 50 evenly spaced elements on a log scale between 2 and 20, exclusive.

In [25]:
x = np.logspace(2,20,50,endpoint=False,base=10.0)
print('x logspace: ',x)

x logspace:  [1.00000000e+02 2.29086765e+02 5.24807460e+02 1.20226443e+03
 2.75422870e+03 6.30957344e+03 1.44543977e+04 3.31131121e+04
 7.58577575e+04 1.73780083e+05 3.98107171e+05 9.12010839e+05
 2.08929613e+06 4.78630092e+06 1.09647820e+07 2.51188643e+07
 5.75439937e+07 1.31825674e+08 3.01995172e+08 6.91830971e+08
 1.58489319e+09 3.63078055e+09 8.31763771e+09 1.90546072e+10
 4.36515832e+10 1.00000000e+11 2.29086765e+11 5.24807460e+11
 1.20226443e+12 2.75422870e+12 6.30957344e+12 1.44543977e+13
 3.31131121e+13 7.58577575e+13 1.73780083e+14 3.98107171e+14
 9.12010839e+14 2.08929613e+15 4.78630092e+15 1.09647820e+16
 2.51188643e+16 5.75439937e+16 1.31825674e+17 3.01995172e+17
 6.91830971e+17 1.58489319e+18 3.63078055e+18 8.31763771e+18
 1.90546072e+19 4.36515832e+19]


## <font color = blue> Problem 2: using numpy and matplotlib to create and view some fake data: a noisy sin wave </font>
#### 2a.) Using np.linspace, create a 1D array "t" containing 1000 evenly spaced elements between 0 and 1, exclusive. Print the first 50 elements to check that your 1D array has values incrementing by 0.001.

In [30]:
t = np.linspace(0,1,1000,endpoint=True)
print('t[0:50]: ',t[0:50])

t[0:50]:  [0.         0.001001   0.002002   0.003003   0.004004   0.00500501
 0.00600601 0.00700701 0.00800801 0.00900901 0.01001001 0.01101101
 0.01201201 0.01301301 0.01401401 0.01501502 0.01601602 0.01701702
 0.01801802 0.01901902 0.02002002 0.02102102 0.02202202 0.02302302
 0.02402402 0.02502503 0.02602603 0.02702703 0.02802803 0.02902903
 0.03003003 0.03103103 0.03203203 0.03303303 0.03403403 0.03503504
 0.03603604 0.03703704 0.03803804 0.03903904 0.04004004 0.04104104
 0.04204204 0.04304304 0.04404404 0.04504505 0.04604605 0.04704705
 0.04804805 0.04904905]


#### 2b.) Using numpy's sin function, create a sin wave equal to $sin = sin(2\pi * (4*t))$, and a 1D array "noise", the same shape as your sin array,  filled with random float values between -1 and 1. Set a third array "noisy_sin" = <code>sin + noise</code>.  

In [40]:
#hint: use np.pi for your sin wave
#hint: randint, which lets you input a range, will only output integers
#you can normalize to [-1,1] via 2*(x-x.min()/x.max()-x.min())-1
sin = np.sin(2*np.pi*(4*t))
noise = np.random.random(sin.shape)
noise = 2*(noise-noise.min()/noise.max()-noise.min())-1
print('noise: ',noise[1:10],'\nmin / max: ',noise.min(),'/ ',noise.max())
noisy_sin = sin + noise
print('noisy_sin: ',noisy_sin[1:10])

noise:  [ 0.91888616 -0.21791429  0.92834133  0.36714159 -0.54037947 -0.37622906
 -0.94784901 -0.83517173 -0.16824966] 
min / max:  -1.0011972996753444 /  0.9959514442517341
noisy_sin:  [ 0.94404141 -0.16761971  1.00374339  0.46760343 -0.41492144 -0.22585423
 -0.77265257 -0.63526454  0.05624175]


 #### 2d.) In two plots (use subplots), plot <code>(t, sin)</code> in red and <code>(t, noisysin)</code> in blue. Title plots appropriately, including the frequency of the wave that you've generated!

## <font color = blue> Problem 3: Using SciPy to construct/apply a filter </font>
### Before begining, the problem, go back up to your first cell and import signal from scipy.
#### 3a.) Using SciPy.signal's butterworth filter function (scipy.signal.butter: documentation [here](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.butter.html)), create a <font color = red>2nd order</font>,<font color = red> low-pass</font>,<font color = red> analog</font> filter with a cutoff frequency of <font color = red>10 rad/s</font>.

In [145]:
#hint: signal.butter returns TWO outputs - you'll want to set it equal to two
#comma-separated variables. This is demonstrated clearly in the documentation!


#### 3b.) Using SciPy.signal's freq function (documentation [here](https://docs.scipy.org/doc/scipy-0.16.0/reference/generated/scipy.signal.freqs.html)), to compute the frequency response of the filter that you generated in 3a.

In [1]:
#Similarly, the documentation givesa very thorough example!



#### 3c.) Passing the input <code>(w, 20 * np.log10(abs(h)))</code> into plt.plot (and setting the x-axis to logscale) or plt.semilogx, plot your filter in log-scale. Title and label axes appropriately. Use matplotlib's "grid" method to include a grid background from <font color = red> both </font> the x and y axes.

#### 3d.) Once again, use signal.butter() to create a filter. This time, create a <font color=red>second order, low-pass </font> <font color=orange> digital filter</font><font color=red> with a frequency cutoff of 10Hz</font>  filter. In this case, the frequency cutoff must be __normalized__ . We can do this by dividing our desired cutoff frequency in __Hz__ by half the sampling frequency! As each timestep in "t" = 0.001, our sampling frequency is 1000.
<br> 
#### To make this code readable to future users, assign the sampling frequency to a variable "fs" and comment your code well.

#### 3e.) Finally, by passing the two outputs of your digital filter above and the signal you want filtered into signal.filtfilt(), create a variable called "filtered_signal" that is equal to the noisy sin wave with your digital filter applied to it! 
<br><br>
#### Using 4x1 subplots, plot your (1) initial sin wave in blue, (2) your noisy sin wave in orange, (3) your filtered noisy sin wave in green, and (4) all three overlaid.